### ISSUE TITLE
user_custom for sandbox testing not working

### ISSUE THREAD

**Issue by snavarro89** [plaid/sandbox-custom-users#1]
I am trying to load a customer user with a specific starting balance and I have done two things 

1) Configure a new user from the sandbox dashboard with my custom JSON configuration object
2) Use "user_custom" user and set the password to configuration object

All the time I get a $100 savings account and a $200 Checking Account. 

Is there a step I am missing?

I am grabbing one of the examples of this repo and just adding the "starting_balance" property.

**Comment by phoenixy1** [comment]
I think you might be misreading the instructions if I'm understanding correctly what you're doing. Basically, there are two different ways to create a custom user, and I think you're accidentally combining them. 
The steps are:
1. Configure a new user from the sandbox dashboard with the custom configuration object. You'll be prompted to save this user with a name that starts with the string `custom_`. For example, `custom_balance`.
2. When logging in as the test user, use the user name you picked in step 1 (e.g. `custom_balance`) and then use any non-empty password.

**Comment by snavarro89** [comment]
I did understand the two ways and I believe I am not combining them. 
Im attaching pictures of the process
My user "custom_sam" has a custom json, so I'm expecting the starting balance to be $50,000 for savings account. 
When I login I set the user to custom_sam + password = 12345, the savings account balance is $100.

Alternatively as a the second option mentions, when I use the user name "custom_user" and the password I copy paste the whole content of json object, still the savings account balance is set to $200.

<img width="721" alt="Screen Shot 2022-10-11 at 18 54 11" src="https://user-images.githubusercontent.com/19916316/195219221-6c73dccc-c02e-446e-83fc-fb3c2da9741e.png">
<img width="636" alt="Screen Shot 2022-10-11 at 18 55 07" src="https://user-images.githubusercontent.com/19916316/195219229-ff837bf7-81bd-4523-9527-e23e2e9fb841.png">
<img width="756" alt="Screen Shot 2022-10-11 at 18 55 48" src="https://user-images.githubusercontent.com/19916316/195219230-60fccb27-61eb-41af-8dff-dc86238f9994.png">
<img width="614" alt="Screen Shot 2022-10-11 at 18 55 57" src="https://user-images.githubusercontent.com/19916316/195219231-1efe30ca-8d31-4d85-ae40-0f64ed231b36.png">

**Comment by phoenixy1** [comment]
@snavarro89 thank you for the detailed report! Now that you've included the screenshots I understand what's happening. Currently, Plaid does not support custom users for OAuth-based institutions. This is functionality we are in the process of adding, and it should be available very soon. In the meantime, if you use a non-OAuth institution, you should find that the custom user works correctly.

**Comment by snavarro89** [comment]
I'm using the quickstart example from github, is there a way to display non O-Auth institutions?

**Comment by snavarro89** [comment]
You have been very helpful Alex, thanks for the info. I'll wait for OAuth to be released.

**Comment by phoenixy1** [comment]
@snavarro89 BTW one clarification about something I got wrong earlier -- the bug around custom Sandbox users and OAuth specifically only affects the display of balances within the Link UI. If you complete the Link flow and call an endpoint, the data should be returned correctly.

**Comment by oguzhantx** [comment]
When I try to add an institution with my custom account on a non OAuth institution, I am getting credentials_error_id in the response. What am I missing here? 
![image](https://github.com/plaid/sandbox-custom-users/assets/94402055/107bcd99-7465-4fb7-ba9e-c00de58b61c7)

just FYI, I have created the custom account in sandbox dashboard with the custom configuration object.

**Comment by phoenixy1** [comment]
@oguzhantx it's not possible to answer that with the information provided.  Please create a new issue on a new thread with full, detailed repro steps, and we can take a look! Also, please confirm that this only happens when using a custom user and not `user_good`

**Comment by oguzhantx** [comment]
> @oguzhantx it's not possible to answer that with the information provided. Please create a new issue on a new thread with full, detailed repro steps, and we can take a look! Also, please confirm that this only happens when using a custom user and not `user_good`

created a new issue and tried to add some repro steps. https://github.com/plaid/sandbox-custom-users/issues/11
