### ISSUE TITLE
custom_user authentication fails

### ISSUE THREAD

**Issue by oguzhantx** [plaid/sandbox-custom-users#11]
Hello, 

I am trying to create and utilize a custom user via sandbox dashboard.
![image](https://github.com/plaid/sandbox-custom-users/assets/94402055/f87910ca-c4de-491d-959b-4825da39b9b6)

When I try to add a new institution and use my custom user credentials (username: custom_oz, password: test) I am getting a credentials error id. 
![image](https://github.com/plaid/sandbox-custom-users/assets/94402055/87f1fb3b-921b-4b49-88cf-c082fdd3885d)

+I am trying with non-OAuth institution 
+user_good works fine

**Comment by phoenixy1** [comment]
@oguzhantx I was not able to reproduce this following the steps above. To help us out, can you provide:
1) the exact config file you are using for the custom user
2) the request body you are sending to /link/token/create (with your client id and secret redacted, of course)  
3) the specific bank you are using 
thanks!

**Comment by phoenixy1** [comment]
Closing this out for now as nrep -- if you add the requested details we can try again.

**Comment by oguzhantx** [comment]
> @oguzhantx I was not able to reproduce this following the steps above. To help us out, can you provide:
> 
> 1. the exact config file you are using for the custom user
> 2. the request body you are sending to /link/token/create (with your client id and secret redacted, of course)
> 3. the specific bank you are using
>    thanks!

Got this working
