### ISSUE TITLE
Inconsistent transactions returned?

### ISSUE THREAD

**Issue by jclaessens97** [plaid/sandbox-custom-users#19]
Hi, I'm trying to write some integration tests for my API, but when using sandbox the transactions returned are not consistent, even though I added them as an override.

```json
{
  "override_accounts": [
    {
      "starting_balance": 1000,
      "meta": {
        "name": "Plaid Checking",
        "mask": "0000"
      },
      "type": "depository",
      "subtype": "checking",
      "transactions": [
        {
          "date_transacted": "2024-03-02",
          "date_posted": "2024-03-03",
          "amount": 400,
          "description": "DEBIT CRD AUTOPAY 98712 000000000098712 WRSGTKIUYPKF KJHAUXYOTLL A",
          "currency": "USD"
        },
        {
          "date_transacted": "2024-01-04",
          "date_posted": "2024-01-05",
          "amount": -200,
          "description": "CREDIT CRD AUTOPAY 29812 000000000098123 KABCRGKSPKFG YOTALDUXZYA B",
          "currency": "USD"
        }
      ]
    }
  ]
}
```

And I use it here:
```typescript
public static async createSandboxPublicToken() {
  const response = await this.plaid.sandboxPublicTokenCreate({
    institution_id: 'ins_109508',
    initial_products: [Products.Auth, Products.Transactions],
    options: {
      override_username: 'user_custom',
      override_password: JSON.stringify({
        ...plaidSandboxTransaction,
      }),
    },
  });
  return response.data.public_token;
}
```

But still, the transaction is sometimes returned but more often not than it is... The account itself is consistently returned and if I change something there it mirrors the change immediately. Any idea? Thanks!

**Comment by phoenixy1** [comment]
Can you clarify exactly what the expected and actual behavior you are seeing is, including the exact requests and responses from the transactions endpoint?

**Comment by jclaessens97** [comment]
Hi, I created a repro here: https://github.com/jclaessens97/plaid-sandbox-tx-repro

Since I add 2 hardcoded transactions in override, I would expect there to consistently be 2 transactions returned. However most of the time it's none. Sometimes there is indeed the 2 I added.

**Comment by phoenixy1** [comment]
Thank you for the repro! This is a race condition in your code -- returning 0 transactions is expected behavior when `/transactions/sync` is called too early, before any transactions webhooks have fired. https://plaid.com/docs/transactions/troubleshooting/#no-transactions-or-cursor-returned

**Comment by jclaessens97** [comment]
Thanks! Completely missed that page in the docs.
