### ISSUE TITLE
Feature request: example for mortgage-type liabilities

### ISSUE THREAD

**Issue by sardine8042** [plaid/sandbox-custom-users#2]
Hello!

Can we get an example of a mortgage-type loan?

I've tried something like this:
```
    {
      "type": "loan",
      "subtype": "mortgage",
      "liability": {
        "type": "mortgage",
        "current_late_fee": 25,
        "escrow_balance": 3141.54,
        "has_pmi": true,
        "has_prepayment_penalty": true,
        "interest_rate": {
          "percentage": 3.99,
          "type": "fixed"
        },
        "last_payment_amount": 3141.54,
        "last_payment_date": "2019-08-01",
        "loan_term": "30 year",
        "loan_type_description": "conventional",
        "maturity_date": "2045-07-31",
        "next_monthly_payment": 3141.54,
        "next_payment_due_date": "2019-11-15",
        "origination_date": "2015-08-01",
        "origination_principal_amount": 425000,
        "past_due_amount": 2304,
        "ytd_interest_paid": 12300.4,
        "ytd_principal_paid": 12340.5
      }
```

However, when I try to create a custom user with this, I get the following error message: `invalid value for field "liability.type": "mortgage"`. An example would be very helpful. Thanks!

**Comment by phoenixy1** [comment]
@sardine8042 mortgages are not currently supported in the custom Sandbox, see https://plaid.com/docs/sandbox/user-custom/#UserCustomPassword-override-accounts-liability-type but we're currently working on some sandbox improvements; if you let me know where you work / what company you're with i can put this feedback into our feedback tracker!
