### ISSUE TITLE
Injecting data to sandbox using API

### ISSUE THREAD

**Issue by adibrastegarniagithub** [plaid/sandbox-custom-users#28]
Can data be injected into the sandbox via an API, or is the dashboard the only method for doing so?

**Comment by phoenixy1** [comment]
This can be done via API, see https://plaid.com/docs/sandbox/user-custom/#configuring-the-custom-user-account

"Custom user accounts can be configured and accessed in two ways. The easiest (and recommended) method is by using the [Sandbox Users](https://dashboard.plaid.com/developers/sandbox?tab=testUsers) tool, located in the Plaid Dashboard under Developers -> Sandbox. Set the username and [configuration object](https://plaid.com/docs/sandbox/user-custom/#configuration-object-schema) in the Dashboard, then go through the Link flow on Sandbox with that username and any non-empty password. You can also use [/sandbox/public_token/create](https://plaid.com/docs/api/sandbox/#sandboxpublic_tokencreate) with options.override_username and options.override_password to create a public token for a custom user account while bypassing Link. Alternatively, you can log into Sandbox with the username user_custom and provide the [configuration object](https://plaid.com/docs/sandbox/user-custom/#configuration-object-schema) as the password."

Note that some products are not supported by `/sandbox/public_token/create`; for those products you won't be able to inject the data via API.
