### ISSUE TITLE
Payroll type accounts are not documented

### ISSUE THREAD

**Issue by sardine8042** [plaid/sandbox-custom-users#3]
Hello!

There's a couple examples in this repository that specify the account type as `payroll`. However, according to the account type schema documentation here: https://plaid.com/docs/api/accounts/#account-type-schema, the only possible values for this are `credit`, `depository`, `loan`, and `other`. It seems `payroll` is only valid in the sub-type field.

Should that documentation be updated?

Thanks!

**Comment by phoenixy1** [comment]
@sardine8042 I think the heart of this question is similar to your other ticket, which is that the schema for accounts used by the custom user object is not exactly the same as the schema for accounts used by the Plaid API. For the custom user object schema documentation, refer to https://plaid.com/docs/sandbox/user-custom/#configuration-object-schema . `payroll` is supported as an account type for the custom user object schema, but not for the Plaid API. I'll make sure to link to this documentation in the readme for this repo as well.
